baseURL = 'http://mlavi.github.io/'
url = 'http://mlavi.github.io/'
languageCode = 'en-us'
title = "Mark's Blog"
author = "Mark Lavi"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
theme = 'hugo-redlounge.mod'
RelativeURLs = true
nocomment = true
noread = true
authorlinkedin = 'http://www.linkedin.com/in/marklavi'
# git submodule add git@github.com:mlavi/mlavi.github.io.git public
