baseURL = 'https://mlavi.github.io/'
url = 'https://mlavi.github.io/'
languageCode = 'en-us'
title = "Mark's Blog"
author = "Mark Lavi"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
theme = 'hugo-redlounge.mod'
RelativeURLs = true
nocomment = true
noread = true
authorlinkedin = 'http://www.linkedin.com/in/marklavi'
enableGitInfo = true 
# git submodule add git@github.com:mlavi/mlavi.github.io.git public
# https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
